name: Android v7 Optimized

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout_code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: install_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf cmake libtool ninja-build p7zip-full pkg-config wget python3

      - name: setup_ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: build_sdk_v7
        working-directory: ${{github.workspace}}/Build
        run: |
          make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=ON -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install-v7" android-armeabi-v7a 2>&1 | tee build_output_log.txt
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: export_artifacts
        if: always()
        run: |
          mkdir -p final_output/binaries
          mkdir -p final_output/logs
          
          cp Build/build_output_log.txt final_output/logs/ || true
          
          find . -name "libTeamTalk5*jni.so" ! -name "*Pro*" -exec cp {} final_output/binaries/ \; || true
          
          mkdir -p final_output/teamtalk_headers
          find Library/ -name "*.h" -exec cp --parents {} final_output/teamtalk_headers/ \; || true

      - name: upload_results
        uses: actions/upload-artifact@v7
        with:
          name: TeamTalk-v7-Offline-Package
          path: final_output/