name: Android v8a Offline Builder

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: disk_cleanup
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo docker image prune --all --force
          sudo apt-get clean

      - name: check_disk_space
        run: |
          echo "============================================"
          echo "CURRENT DISK USAGE:"
          df -h | grep '^/dev/'
          echo "============================================"

      - name: checkout_code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf cmake libtool ninja-build p7zip-full pkg-config wget python3

      - name: setup_ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: build_sdk_v8
        working-directory: ${{github.workspace}}/build
        run: |
          # با افزودن فلگ‌های LIBPRO=OFF نسخه پرو بیلد نمی‌شود
          make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=ON -DBUILD_TEAMTALK_LIBRARY_LIBPRO=OFF -DBUILD_TEAMTALK_LIBRARY_DLLPRO=OFF" android-arm64-v8a
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: export_artifacts
        if: always()
        working-directory: ${{github.workspace}}
        run: |
          mkdir -p output_v8/TeamTalk_Binaries
          mkdir -p output_v8/TeamTalk_Headers
          
          # فقط نسخه استاندارد کپی می‌شود
          cp Library/TeamTalk_DLL/arm64-v8a/libTeamTalk5.so output_v8/TeamTalk_Binaries/ || true
          
          # کپی هدرها با حفظ ساختار
          find Library/ -name "*.h" -print0 | xargs -0 -I {} cp --parents {} output_v8/TeamTalk_Headers/ || true
          
          # کپی پوشه install پیش‌نیازها که برای بیلد آفلاین حیاتی است
          cp -r build/build-release-android-arm64-v8a/install output_v8/Prebuilt_Toolchain || true

      - name: upload_results
        uses: actions/upload-artifact@v4
        with:
          name: TeamTalk-v8a-Offline-Deps
          path: output_v8/