name: Android v8

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: disk_cleanup
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo docker image prune --all --force
          sudo apt-get clean

      - name: check_disk_space
        run: |
          echo "============================================"
          echo "CURRENT DISK USAGE:"
          df -h | grep '^/dev/'
          echo "============================================"

      - name: checkout_code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf cmake libtool ninja-build p7zip-full pkg-config wget python3

      - name: setup_ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: build_sdk_v8
        # خط working-directory پاک شد تا دستور مستقیما در کنار فایل Makefile اجرا شود
        run: |
          make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=ON" android-arm64-v8a
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: export_artifacts
        if: always()
        run: |
          mkdir -p output_v8/libs
          mkdir -p output_v8/headers
          
          # فقط نسخه استاندارد کپی می‌شود (نسخه Pro نادیده گرفته می‌شود)
          cp Library/TeamTalk_DLL/arm64-v8a/libTeamTalk5.so output_v8/libs/ || true
          
          # کپی هدرهای خود تیم‌تاک با حفظ ساختار
          find Library/ -name "*.h" -exec cp --parents {} output_v8/headers/ \; || true
          
          # تمام فایل‌های .a و هدرهای پیش‌نیاز مرتب شده برای استفاده آفلاین
          cp -r build-release-android-arm64-v8a/install output_v8/Prebuilt_Toolchain || true

      - name: upload_results
        uses: actions/upload-artifact@v4
        with:
          name: TeamTalk-v8-SDK
          path: output_v8/