name: Android v7

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: disk_cleanup
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo docker image prune --all --force
          sudo apt-get clean

      - name: check_disk_space
        run: |
          echo "============================================"
          echo "CURRENT DISK USAGE:"
          df -h | grep '^/dev/'
          echo "============================================"

      - name: checkout_code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf cmake libtool ninja-build p7zip-full pkg-config wget python3

      - name: setup_ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: build_sdk_v7
        working-directory: ${{github.workspace}}/Build
        run: |
          make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=ON -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install-android" android-armeabi-v7a
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: export_artifacts
        if: always()
        run: |
          mkdir -p output_v7/libs
          mkdir -p output_v7/headers
          cp -r Library/TeamTalk_DLL/armeabi-v7a/*.so output_v7/libs/ || true
          find Build/build-release-android-armeabi-v7a/ -name "*.a" -exec cp {} output_v7/libs/ \; || true
          find Library/ -name "*.h" -exec cp --parents {} output_v7/headers/ \; || true

      - name: upload_results
        uses: actions/upload-artifact@v4
        with:
          name: TeamTalk-v7-SDK
          path: output_v7/