name: Android v8 Secure (O-MVLL)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf cmake libtool ninja-build p7zip-full pkg-config wget python3 python3-pip
          pip3 install pyelftools --break-system-packages

      - name: setup_ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: build_sdk_v8
        working-directory: ${{github.workspace}}/Build
        run: |
          make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=ON" android-arm64-v8a
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: export_artifacts
        if: always()
        run: |
          mkdir -p final_output/binaries
          find Build/ -name "*.so" -exec cp {} final_output/binaries/ \; || true
          
          mkdir -p final_output/teamtalk_headers
          find Library/ -name "*.h" -exec cp --parents {} final_output/teamtalk_headers/ \; || true

      - name: upload_results
        uses: actions/upload-artifact@v4
        with:
          name: TeamTalk-v8-Secure-Package
          path: final_output/