name: Android v8 Secure (No Pro)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf cmake libtool ninja-build p7zip-full pkg-config wget python3 python3-pip
          pip3 install pyelftools --break-system-packages

      - name: Download O-MVLL Plugin
        run: |
          echo "Downloading O-MVLL 1.6.0..."
          wget https://github.com/open-obfuscator/o-mvll/releases/download/1.6.0/omvll_v1-6-0_linux_2026-04-23T13_47_22.tar.gz
          tar -xzf omvll_v1-6-0_linux_2026-04-23T13_47_22.tar.gz
          find . -name "omvll-ndk.so" -exec cp {} . \;
          chmod +x omvll-ndk.so
          ls -l omvll-ndk.so
          

          sudo mkdir -p /cpython-install
          
          PYTHON_SRC_DIR=$(find $(pwd) -name "Python-3.10.7" -type d | head -n 1)
          echo "Python source found at: $PYTHON_SRC_DIR"
          
          sudo cp -rv $PYTHON_SRC_DIR/* /cpython-install/
          
          echo "Checking if encodings exists..."
          ls -d /cpython-install/lib/python3.10/encodings || echo "ERROR: encodings folder not found in target!"
          
          sudo chmod -R 755 /cpython-install

      - name: setup_ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: build_sdk_v8
        working-directory: ${{github.workspace}}/Build
        run: |
          make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=ON" android-arm64-v8a
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: export_artifacts
        if: always()
        run: |
          mkdir -p final_output/binaries
          find Build/ -name "*jni.so" ! -name "*Pro*" -exec cp {} final_output/binaries/ \; || true
          
          mkdir -p final_output/teamtalk_headers
          find Library/ -name "*.h" -exec cp --parents {} final_output/teamtalk_headers/ \; || true

      - name: upload_results
        uses: actions/upload-artifact@v4
        with:
          name: TeamTalk-v8-Secure-Standard
          path: final_output/